image: ubuntu:14.04

# Define commands that run before each job's script
before_script:
  - apt-get update
  - apt-get install -y gcc g++
  - apt-get install software-properties-common
  - add-apt-repository ppa:george-edison55/cmake-3.x
  - apt-get update
#When cmake is not yet installed:

  - apt-get install cmake
#When cmake is already installed:
  - apt-get upgrade

# Try to compile our sample hello world app
compile:
  script:
  # скрипт сборки и тестирования проекта:
  - mkdir build
  - cd build
  - cmake .. -DCMAKE_BUILD_TYPE=amd64=Release
  - cmake --build .
  - ctest --output-on-failure
  artifacts:
    paths:
    - helloworld
